# golangci-lint configuration for zen-flow
# Minimal config for v2.7.2 compatibility

version: "2"

run:
  timeout: 5m
  tests: true
  go: "1.25"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - misspell
    - gocyclo
    - gosec
    - goimports

